---
  - name: Install Packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - java-1.8.0
      - python3
      - python3-pip
  
  - name: Install pip packages
    pip:
      name: "{{ item }}"
      executable: pip3
    loop:
      - boto3
      - botocore   

  - name: Download Tomcat
    get_url:
      url: "{{Tomcat_download_url}}"
      dest: "{{Tomcat_download_dest}}"
      mode: 0777
      owner: "{{tomcat_app_owner}}"
      group: "{{tomcat_app_group}}"

  - name: Extract Tomcat
    unarchive:
      src: "{{Tomcat_download_dest}}"
      dest: "{{Tomcat_download_dest}}"
      owner: "{{tomcat_app_owner}}"
      group: "{{tomcat_app_group}}"
      remote_src: yes

  - name: Copy tomcat users file to tomcat server
    copy:
      src: tomcat-users.xml
      dest: "{{tomcat_userfile_dest}}"

  - name: Copy context.xml
    copy:
      src: context.xml
      dest: "{{tomcat_contextfile_dest}}"


  - name: Stop Tomcat server
    shell: ./shutdown.sh
    args:
      chdir: "{{Tomcat_download_dest}}/bin"

  - name: Deploy Gameof Life.war
    amazon.aws.s3_object:
      access_key: "{{Access_key}}"
      secret_key: "{{Secret_Key}}"
      bucket: "{{bucket-name}}"
      object: "{{name of artifact}}"
      dest: "{{Tomcat_download_dest}}/webapps/gameoflife.war"
      mode: get      
      
  - name: Start Tomcat
    shell: ./startup.sh
    args:
      chdir: "{{Tomcat_download_dest}}/bin"

      
